[Variables]
TotalGame=14

Gamename1=Photos
Gamecover1=Photo.png
Gamewall1=Photo.jpg
Gamedir1=shell:appsFolder\Microsoft.Windows.Photos_8wekyb3d8bbwe!App

Gamename2=Chrome
Gamecover2=chrome.png
Gamedir2=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Gamewall2=chrome.jpg

Gamename3=After Effect
Gamecover3=ae.png
Gamedir3=C:\Program Files\Adobe\Adobe After Effects CC 2018\Support Files\AfterFX.exe
Gamewall3=ae.png

Gamename4=GM:Studio
Gamecover4=gms.png
Gamewall4=gms.jpg
Gamedir4=D:\Program Files\GameMaker-Studio\Startilla_V3.exe

Gamename5=Photoshop
Gamecover5=ps.png
Gamewall5=ps.jpg
Gamedir5=C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe

Gamename6=Movies
Gamecover6=movie.png
Gamewall6=movie.jpg
Gamedir6=#@#VLC.lnk
;Gamedir6=shell:appsFolder\Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo

Gamename7=Unity
Gamecover7=unity.png
Gamewall7=unity.jpg
Gamedir7=D:\Program Files\Editor\Unity.exe

Gamename8=Discord
Gamecover8=discord.png
Gamewall8=discord.jpg
Gamedir8=C:\Users\siegw\AppData\Local\Discord\Update.exe" "--processStart" "Discord.exe

Gamename9=Groove Music
Gamecover9=music.png
Gamewall9=music.jpg
Gamedir9=shell:appsFolder\Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic

Gamename10=My office
Gamecover10=office.png
Gamewall10=office.jpg
Gamedir10=shell:appsFolder\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe!Microsoft.MicrosoftOfficeHub

Gamename11=This PC
Gamecover11=PC.png
Gamewall11=PC.jpg
Gamedir11=#@#PC.lnk

Gamename12=Setting
Gamecover12=setting.png
Gamewall12=setting.jpg
Gamedir12=ms-settings:

Gamename13=Restart
Gamecover13=restart.png
Gamewall13=restart.jpg
Gamedir13=#@#Restart.lnk

Gamename14=Shutdown
Gamecover14=shutdown.png
Gamewall14=shutdown.jpg
Gamedir14=#@#Shutdown.lnk

Gamename15=Photos
Gamecover15=Photo.png
Gamewall15=Photo.jpg
Gamedir15=shell:appsFolder\Microsoft.Windows.Photos_8wekyb3d8bbwe!App

Gamename16=Chrome
Gamecover16=chrome.png
Gamedir16=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Gamewall16=chrome.jpg

Gamename17=GM:Studio
Gamecover17=gms.png
Gamedir17=D:\Program Files\GameMaker-Studio\Startilla_V3.exe
Gamewall17=gms.jpg

Gamename18=After Effect
Gamecover18=ae.png
Gamewall18=ae.png
Gamedir18=C:\Program Files\Adobe\Adobe After Effects CC 2018\Support Files\AfterFX.exe

Gamename19=Photoshop
Gamecover19=ps.png
Gamewall19=ps.jpg
Gamedir19=C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe

Gamename20=Movies
Gamecover20=movie.png
Gamewall20=movie.jpg
Gamedir20=shell:appsFolder\Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo
