[Variables]
TotalGame=14

Gamename1=Batman: Arkham Knight 
Gamecover1=arkhamknight.png
Gamewall1=arkhamknight.jpg
Gamedir1=D:\Program Files\Batman - Arkham Knight\Binaries\Win64\BatmanAK.exe

Gamename2=Warframe
Gamecover2=warframe.png
Gamedir2=C:\Users\Finch\AppData\Local\Warframe\Downloaded\Test\Tools\Launcher.exe
Gamewall2=warframe.png

Gamename3=Nier Automata
Gamecover3=nier.png
Gamedir3=D:\Program Files\NieR - Automata\NieRAutomata.exe
Gamewall3=nier.jpg

Gamename4=Final Fantasy XV
Gamecover4=ffxv.png
Gamewall4=ffxv.jpg
Gamedir4=D:\Program Files\FFXV\ffxv_s.exe

Gamename5=The Witcher 3 - Wild Hunt
Gamecover5=witcher3.png
Gamewall5=witcher3.png
Gamedir5=D:\Program Files\The Witcher 3 - Wild Hunt\bin\x64\witcher3.exe

Gamename6=Fallout 4
Gamecover6=fallout4.png
Gamewall6=fallout4.jpg
Gamedir6=D:\Program Files\Fallout 4\f4se_loader.exe

Gamename7=Battlefield 4
Gamecover7=bf4.png
Gamewall7=bf4.jpg
Gamedir7=D:\Program Files\Battlefield 4\bf4.exe

Gamename8=Kerbal Space Program
Gamecover8=kerbal.png
Gamewall8=kerbal.jpg
Gamedir8=D:\Program Files\Kerbal Space Program Making History\KSP_x64.exe

Gamename9=Call of Duty World War 2
Gamecover9=codww2.png
Gamewall9=codww2.jpg
Gamedir9=D:\Program Files\Call of Duty - WWII\CoD_SP.exe

Gamename10=Watch Dogs 2
Gamecover10=wd2.png
Gamewall10=wd2.jpg
Gamedir10=D:\Program Files\Watch Dogs 2\bin\WatchDogs2.exe

Gamename11=The sims 4
Gamecover11=sims4.png
Gamewall11=sims4.jpg
Gamedir11=D:\Program Files\The Sims 4\Game\Bin\TS4_x64.exe

Gamename12=Minecraft
Gamecover12=minecraft.png
Gamewall12=minecraft.jpg
Gamedir12=C:\Users\Finch\AppData\Roaming\.minecraft\MinecraftLauncher.exe

Gamename13=Hellblade: Senua's Sacrifice
Gamecover13=hellblade.png
Gamewall13=hellblade.jpg
Gamedir13=D:\Program Files\Hellblade - Senua's Sacrifice\HellbladeGame.exe

Gamename14=Stardew Valley
Gamecover14=sv.png
Gamewall14=sv.jpg
Gamedir14=D:\Program Files\Stardew.Valley.v1.3.27\StardewModdingAPI.exe

Gamename15=
Gamecover15=default.png
Gamewall15=default.png
Gamedir15=

Gamename16=
Gamecover16=default.png
Gamewall16=default.png
Gamedir16=

Gamename17=
Gamecover17=default.png
Gamewall17=default.png
Gamedir17=

Gamename18=
Gamecover18=default.png
Gamewall18=default.png
Gamedir18=

Gamename19=
Gamecover19=default.png
Gamewall19=default.png
Gamedir19=

Gamename20=
Gamecover20=default.png
Gamewall20=default.png
Gamedir20=

Gamename21=
Gamecover21=default.png
Gamewall21=default.png
Gamedir21=

Gamename22=
Gamecover22=default.png
Gamewall22=default.png
Gamedir22=

Gamename23=
Gamecover23=default.png
Gamewall23=default.png
Gamedir23=

Gamename24=
Gamecover24=default.png
Gamewall24=default.png
Gamedir24=

Gamename25=
Gamecover25=default.png
Gamewall25=default.png
Gamedir25=

Gamename26=
Gamecover26=default.png
Gamewall26=default.png
Gamedir26=

Gamename27=
Gamecover27=default.png
Gamewall27=default.png
Gamedir27=

Gamename28=
Gamecover28=default.png
Gamewall28=default.png
Gamedir28=

Gamename29=
Gamecover29=default.png
Gamewall29=default.png
Gamedir29=

Gamename30=
Gamecover30=default.png
Gamewall30=default.png
Gamedir30=

Gamename31=
Gamecover31=default.png
Gamewall31=default.png
Gamedir31=
