[Variables]

;		- Note -
;	If your secondary monitor is on the left
;	Set skin X position to negative

SkinWidth=#SCREENAREAWIDTH#
SkinHeight=#SCREENAREAHEIGHT#
SkinX=0
SkinY=0

ScrollMultiplier=0.96
CoverSolid=30,30,30,80
Color=255,255,255
LineAlpha=100
TitleScale=(Clamp(#SkinWidth#/36,12,60))
Font=Source Sans Pro ExtraLight
NameY=20
Editing=7
Mode=0
scrollbar=1
material=1
NameSize=20

steam=1
origin=1
uplay=1
battlenet=0
epicgames=0

keyboard=1
gamepad=1

ButtonAction=[!ActivateConfig GameHUB\Wizard help.ini]
ScrollDivider=9.4
Wall=      
