[Game1] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover1# 
X=([SmoothScroll])+(#Space#)*Trunc(0/#Rows#) 
Y=((0%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "1"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 1"] 
  
[Game2] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover2# 
X=([SmoothScroll])+(#Space#)*Trunc(1/#Rows#) 
Y=((1%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "2"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 2"] 
  
[Game3] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover3# 
X=([SmoothScroll])+(#Space#)*Trunc(2/#Rows#) 
Y=((2%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "3"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 3"] 
  
[Game4] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover4# 
X=([SmoothScroll])+(#Space#)*Trunc(3/#Rows#) 
Y=((3%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "4"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 4"] 
  
[Game5] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover5# 
X=([SmoothScroll])+(#Space#)*Trunc(4/#Rows#) 
Y=((4%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "5"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 5"] 
  
[Game6] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover6# 
X=([SmoothScroll])+(#Space#)*Trunc(5/#Rows#) 
Y=((5%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "6"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 6"] 
  
[Game7] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover7# 
X=([SmoothScroll])+(#Space#)*Trunc(6/#Rows#) 
Y=((6%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "7"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 7"] 
  
[Game8] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover8# 
X=([SmoothScroll])+(#Space#)*Trunc(7/#Rows#) 
Y=((7%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "8"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 8"] 
  
[Game9] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover9# 
X=([SmoothScroll])+(#Space#)*Trunc(8/#Rows#) 
Y=((8%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "9"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 9"] 
  
[Game10] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover10# 
X=([SmoothScroll])+(#Space#)*Trunc(9/#Rows#) 
Y=((9%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "10"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 10"] 
  
[Game11] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover11# 
X=([SmoothScroll])+(#Space#)*Trunc(10/#Rows#) 
Y=((10%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "11"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 11"] 
  
[Game12] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover12# 
X=([SmoothScroll])+(#Space#)*Trunc(11/#Rows#) 
Y=((11%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "12"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 12"] 
  
[Game13] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover13# 
X=([SmoothScroll])+(#Space#)*Trunc(12/#Rows#) 
Y=((12%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "13"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 13"] 
  
[Game14] 
Meter=Image 
MeterStyle=GameIcon 
ImageName=#@#App\#Gamecover14# 
X=([SmoothScroll])+(#Space#)*Trunc(13/#Rows#) 
Y=((13%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT# 
MouseOverAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "0,0,0,1"][Play "#@#Sounds\Hover.wav"][!SetVariable Select "14"][!ShowMeter "CoverHighlight"] 
MouseLeaveAction=[!SetOption "#CURRENTSECTION#" "SolidColor" "#CoverSolid#"] 
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 14"] 
  
  
[GameTitle1] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(0/#Rows#)+(#BannerWidth#/2) 
Y=((0%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename1# 
  
[GameTitle2] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(1/#Rows#)+(#BannerWidth#/2) 
Y=((1%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename2# 
  
[GameTitle3] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(2/#Rows#)+(#BannerWidth#/2) 
Y=((2%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename3# 
  
[GameTitle4] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(3/#Rows#)+(#BannerWidth#/2) 
Y=((3%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename4# 
  
[GameTitle5] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(4/#Rows#)+(#BannerWidth#/2) 
Y=((4%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename5# 
  
[GameTitle6] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(5/#Rows#)+(#BannerWidth#/2) 
Y=((5%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename6# 
  
[GameTitle7] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(6/#Rows#)+(#BannerWidth#/2) 
Y=((6%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename7# 
  
[GameTitle8] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(7/#Rows#)+(#BannerWidth#/2) 
Y=((7%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename8# 
  
[GameTitle9] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(8/#Rows#)+(#BannerWidth#/2) 
Y=((8%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename9# 
  
[GameTitle10] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(9/#Rows#)+(#BannerWidth#/2) 
Y=((9%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename10# 
  
[GameTitle11] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(10/#Rows#)+(#BannerWidth#/2) 
Y=((10%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename11# 
  
[GameTitle12] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(11/#Rows#)+(#BannerWidth#/2) 
Y=((11%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename12# 
  
[GameTitle13] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(12/#Rows#)+(#BannerWidth#/2) 
Y=((12%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename13# 
  
[GameTitle14] 
Meter=String 
MeterStyle=GameTitle 
X=([SmoothScroll])+(#Space#)*Trunc(13/#Rows#)+(#BannerWidth#/2) 
Y=((13%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight# 
Text=#Gamename14# 
  
[InputExecute] 
Measure=Plugin 
Plugin=ActionTimer 
DynamicVariables=1 
ActionList1=Select1|Deactivate 
ActionList2=Select2|Deactivate 
ActionList3=Select3|Deactivate 
ActionList4=Select4|Deactivate 
ActionList5=Select5|Deactivate 
ActionList6=Select6|Deactivate 
ActionList7=Select7|Deactivate 
ActionList8=Select8|Deactivate 
ActionList9=Select9|Deactivate 
ActionList10=Select10|Deactivate 
ActionList11=Select11|Deactivate 
ActionList12=Select12|Deactivate 
ActionList13=Select13|Deactivate 
ActionList14=Select14|Deactivate 
Select1=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir1#"] 
Select2=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir2#"] 
Select3=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir3#"] 
Select4=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir4#"] 
Select5=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir5#"] 
Select6=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir6#"] 
Select7=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir7#"] 
Select8=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir8#"] 
Select9=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir9#"] 
Select10=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir10#"] 
Select11=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir11#"] 
Select12=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir12#"] 
Select13=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir13#"] 
Select14=!Execute [Play "#@#Sounds\Launch.wav"]["#Gamedir14#"] 
Deactivate=[!CommandMeasure Exit "Execute 1" "GameHUB"] 
  
[InputCheck] 
Measure=Calc 
DynamicVariables=1 
Disabled=1 
UpdateDivider=-1 
IfCondition=(#Select#=1) 
IfTrueAction=[Play "#@#Sounds\Hover.wav"][!SetOptionGroup "Icon" "SolidColor" "#CoverSolid#"][!SetOption "Game1" "SolidColor" "0,0,0,1"][!ShowMeter "CoverHighlight"][!SetVariable "OffsetX" "(#OffsetX#<20 ? 20 : #OffsetX#)"] 
IfCondition2=(#Select#>1) 
IfTrueAction2=[Play "#@#Sounds\Hover.wav"][!SetOptionGroup "Icon" "SolidColor" "#CoverSolid#"][!SetOption "Game#Select#" "SolidColor" "0,0,0,1"][!ShowMeter "CoverHighlight"][!SetVariable "OffsetX" "(#OffsetX#<(-#Space#*(Floor((#Select#-1)/#Rows#))+#Shown#) ? Min(-#Space#*Trunc((#Select#-1)/#Rows#)+#Shown#,20) : (#OffsetX#>(-#Space#*(Trunc((#Select#-1)/#Rows#))+#CURRENTCONFIGWIDTH#-#Shown#*2) ? Max(-#Space#*(Trunc((#Select#-1)/#Rows#))+#CURRENTCONFIGWIDTH#-#Shown#*2,#ScrollLimit#) : #OffsetX#))"] 
IfConditionMode=1 
