[GameBack1]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(0/#Rows#)
Y=((0%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall1#
Hidden=1
[Game1]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover1#
X=([SmoothScroll])+(#Space#)*Trunc(0/#Rows#)
Y=((0%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack1"][!SetVariable Select "1"]
MouseLeaveAction=[!HideMeter "GameBack1"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 1"]

[GameBack2]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(1/#Rows#)
Y=((1%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall2#
Hidden=1
[Game2]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover2#
X=([SmoothScroll])+(#Space#)*Trunc(1/#Rows#)
Y=((1%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack2"][!SetVariable Select "2"]
MouseLeaveAction=[!HideMeter "GameBack2"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 2"]

[GameBack3]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(2/#Rows#)
Y=((2%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall3#
Hidden=1
[Game3]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover3#
X=([SmoothScroll])+(#Space#)*Trunc(2/#Rows#)
Y=((2%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack3"][!SetVariable Select "3"]
MouseLeaveAction=[!HideMeter "GameBack3"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 3"]

[GameBack4]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(3/#Rows#)
Y=((3%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall4#
Hidden=1
[Game4]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover4#
X=([SmoothScroll])+(#Space#)*Trunc(3/#Rows#)
Y=((3%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack4"][!SetVariable Select "4"]
MouseLeaveAction=[!HideMeter "GameBack4"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 4"]

[GameBack5]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(4/#Rows#)
Y=((4%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall5#
Hidden=1
[Game5]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover5#
X=([SmoothScroll])+(#Space#)*Trunc(4/#Rows#)
Y=((4%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack5"][!SetVariable Select "5"]
MouseLeaveAction=[!HideMeter "GameBack5"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 5"]

[GameBack6]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(5/#Rows#)
Y=((5%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall6#
Hidden=1
[Game6]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover6#
X=([SmoothScroll])+(#Space#)*Trunc(5/#Rows#)
Y=((5%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack6"][!SetVariable Select "6"]
MouseLeaveAction=[!HideMeter "GameBack6"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 6"]

[GameBack7]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(6/#Rows#)
Y=((6%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall7#
Hidden=1
[Game7]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover7#
X=([SmoothScroll])+(#Space#)*Trunc(6/#Rows#)
Y=((6%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack7"][!SetVariable Select "7"]
MouseLeaveAction=[!HideMeter "GameBack7"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 7"]

[GameBack8]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(7/#Rows#)
Y=((7%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall8#
Hidden=1
[Game8]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover8#
X=([SmoothScroll])+(#Space#)*Trunc(7/#Rows#)
Y=((7%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack8"][!SetVariable Select "8"]
MouseLeaveAction=[!HideMeter "GameBack8"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 8"]

[GameBack9]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(8/#Rows#)
Y=((8%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall9#
Hidden=1
[Game9]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover9#
X=([SmoothScroll])+(#Space#)*Trunc(8/#Rows#)
Y=((8%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack9"][!SetVariable Select "9"]
MouseLeaveAction=[!HideMeter "GameBack9"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 9"]

[GameBack10]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(9/#Rows#)
Y=((9%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall10#
Hidden=1
[Game10]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover10#
X=([SmoothScroll])+(#Space#)*Trunc(9/#Rows#)
Y=((9%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack10"][!SetVariable Select "10"]
MouseLeaveAction=[!HideMeter "GameBack10"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 10"]

[GameBack11]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(10/#Rows#)
Y=((10%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall11#
Hidden=1
[Game11]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover11#
X=([SmoothScroll])+(#Space#)*Trunc(10/#Rows#)
Y=((10%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack11"][!SetVariable Select "11"]
MouseLeaveAction=[!HideMeter "GameBack11"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 11"]

[GameBack12]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(11/#Rows#)
Y=((11%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall12#
Hidden=1
[Game12]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover12#
X=([SmoothScroll])+(#Space#)*Trunc(11/#Rows#)
Y=((11%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack12"][!SetVariable Select "12"]
MouseLeaveAction=[!HideMeter "GameBack12"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 12"]

[GameBack13]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(12/#Rows#)
Y=((12%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall13#
Hidden=1
[Game13]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover13#
X=([SmoothScroll])+(#Space#)*Trunc(12/#Rows#)
Y=((12%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack13"][!SetVariable Select "13"]
MouseLeaveAction=[!HideMeter "GameBack13"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 13"]

[GameBack14]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(13/#Rows#)
Y=((13%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall14#
Hidden=1
[Game14]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover14#
X=([SmoothScroll])+(#Space#)*Trunc(13/#Rows#)
Y=((13%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack14"][!SetVariable Select "14"]
MouseLeaveAction=[!HideMeter "GameBack14"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 14"]

[GameBack15]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(14/#Rows#)
Y=((14%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall15#
Hidden=1
[Game15]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover15#
X=([SmoothScroll])+(#Space#)*Trunc(14/#Rows#)
Y=((14%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack15"][!SetVariable Select "15"]
MouseLeaveAction=[!HideMeter "GameBack15"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 15"]

[GameBack16]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(15/#Rows#)
Y=((15%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall16#
Hidden=1
[Game16]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover16#
X=([SmoothScroll])+(#Space#)*Trunc(15/#Rows#)
Y=((15%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack16"][!SetVariable Select "16"]
MouseLeaveAction=[!HideMeter "GameBack16"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 16"]

[GameBack17]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(16/#Rows#)
Y=((16%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall17#
Hidden=1
[Game17]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover17#
X=([SmoothScroll])+(#Space#)*Trunc(16/#Rows#)
Y=((16%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack17"][!SetVariable Select "17"]
MouseLeaveAction=[!HideMeter "GameBack17"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 17"]

[GameBack18]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(17/#Rows#)
Y=((17%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall18#
Hidden=1
[Game18]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover18#
X=([SmoothScroll])+(#Space#)*Trunc(17/#Rows#)
Y=((17%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack18"][!SetVariable Select "18"]
MouseLeaveAction=[!HideMeter "GameBack18"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 18"]

[GameBack19]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(18/#Rows#)
Y=((18%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall19#
Hidden=1
[Game19]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover19#
X=([SmoothScroll])+(#Space#)*Trunc(18/#Rows#)
Y=((18%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack19"][!SetVariable Select "19"]
MouseLeaveAction=[!HideMeter "GameBack19"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 19"]


[GameBack20]
Meter=Image
MeterStyle=GameCover
X=([SmoothScroll])+(#Space#)*Trunc(19/#Rows#)
Y=((19%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
ImageName=#@#App\Cover\#Gamewall20#
Hidden=1
[Game20]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover20#
X=([SmoothScroll])+(#Space#)*Trunc(19/#Rows#)
Y=((19%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!ShowMeter "GameBack20"][!SetVariable Select "20"]
MouseLeaveAction=[!HideMeter "GameBack20"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 20"]

[GameTitle1]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(0/#Rows#)+(#BannerWidth#/2)
Y=((0%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename1#

[GameTitle2]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(1/#Rows#)+(#BannerWidth#/2)
Y=((1%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename2#

[GameTitle3]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(2/#Rows#)+(#BannerWidth#/2)
Y=((2%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename3#

[GameTitle4]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(3/#Rows#)+(#BannerWidth#/2)
Y=((3%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename4#

[GameTitle5]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(4/#Rows#)+(#BannerWidth#/2)
Y=((4%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename5#

[GameTitle6]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(5/#Rows#)+(#BannerWidth#/2)
Y=((5%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename6#

[GameTitle7]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(6/#Rows#)+(#BannerWidth#/2)
Y=((6%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename7#

[GameTitle8]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(7/#Rows#)+(#BannerWidth#/2)
Y=((7%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename8#

[GameTitle9]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(8/#Rows#)+(#BannerWidth#/2)
Y=((8%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename9#

[GameTitle10]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(9/#Rows#)+(#BannerWidth#/2)
Y=((9%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename10#

[GameTitle11]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(10/#Rows#)+(#BannerWidth#/2)
Y=((10%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename11#

[GameTitle12]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(11/#Rows#)+(#BannerWidth#/2)
Y=((11%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename12#

[GameTitle13]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(12/#Rows#)+(#BannerWidth#/2)
Y=((12%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename13#

[GameTitle14]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(13/#Rows#)+(#BannerWidth#/2)
Y=((13%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename14#

[GameTitle15]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(14/#Rows#)+(#BannerWidth#/2)
Y=((14%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename15#

[GameTitle16]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(15/#Rows#)+(#BannerWidth#/2)
Y=((15%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename16#

[GameTitle17]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(16/#Rows#)+(#BannerWidth#/2)
Y=((16%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename17#

[GameTitle18]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(17/#Rows#)+(#BannerWidth#/2)
Y=((17%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename18#

[GameTitle19]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(18/#Rows#)+(#BannerWidth#/2)
Y=((18%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename19#

[GameTitle20]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(19/#Rows#)+(#BannerWidth#/2)
Y=((19%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename20#

