[Variables]
TotalGame=14

Gamename1=Batman: Arkham Knight 
Gamecover1=arkhamknight.png
Gamewall1=arkhamknight.jpg
Gamedir1=D:\Program Files\Batman - Arkham Knight\Binaries\Win64\BatmanAK.exe

Gamename2=Warframe
Gamecover2=warframe.png
Gamedir2=C:\Users\Finch\AppData\Local\Warframe\Downloaded\Test\Tools\Launcher.exe
Gamewall2=warframe.png

Gamename3=Nier Automata
Gamecover3=nier.png
Gamedir3=D:\Program Files\NieR - Automata\NieRAutomata.exe
Gamewall3=nier.jpg

Gamename4=The Witcher 3 - Wild Hunt
Gamecover4=witcher3.png
Gamewall4=witcher3.png
Gamedir4=D:\Program Files\The Witcher 3 - Wild Hunt\bin\x64\witcher3.exe

Gamename5=Battlefield 4
Gamecover5=bf4.png
Gamewall5=bf4.jpg
Gamedir5=D:\Program Files\Battlefield 4\bf4.exe

Gamename6=Kerbal Space Program
Gamecover6=kerbal.png
Gamewall6=kerbal.jpg
Gamedir6=D:\Program Files\Kerbal Space Program Making History\KSP_x64.exe

Gamename7=Final Fantasy XV
Gamecover7=ffxv.png
Gamewall7=ffxv.jpg
Gamedir7=D:\Program Files\FFXV\ffxv_s.exe

Gamename8=Fallout 4
Gamecover8=fallout4.png
Gamewall8=fallout4.jpg
Gamedir8=D:\Program Files\Fallout 4\f4se_loader.exe

Gamename9=Middle Earth: Shadow of War
Gamecover9=middleearth2.png
Gamewall9=middleearth2.jpg
Gamedir9=D:\Program Files\Middle-Earth - Shadow of War\x64\ShadowOfWar.exe

Gamename10=Watch Dogs 2
Gamecover10=wd2.png
Gamewall10=wd2.jpg
Gamedir10=D:\Program Files\Watch Dogs 2\bin\WatchDogs2.exe

Gamename13=The evil within 2
Gamecover13=tew2.png
Gamewall13=tew2.jpg
Gamedir13=D:\Program Files\The Evil Within 2\TEW2.exe


Gamename12=Minecraft
Gamecover12=minecraft.png
Gamewall12=minecraft.jpg
Gamedir12=C:\Users\Finch\AppData\Roaming\.minecraft\MinecraftLauncher.exe

Gamename11=The sims 4
Gamecover11=sims4.png
Gamewall11=sims4.jpg
Gamedir11=D:\Program Files\The Sims 4\Game\Bin\TS4_x64.exe

Gamename14=Stardew Valley
Gamecover14=sv.png
Gamewall14=sv.jpg
Gamedir14=D:\Program Files\Stardew.Valley.v1.3.27\StardewModdingAPI.exe

Gamename15=Batman: Arkham Knight 
Gamecover15=arkhamknight.png
Gamewall15=arkhamknight.jpg
Gamedir15=D:\Program Files\Batman - Arkham Knight\Binaries\Win64\BatmanAK.exe

Gamename16=Warframe
Gamecover16=warframe.png
Gamedir16=C:\Users\Finch\AppData\Local\Warframe\Downloaded\Test\Tools\Launcher.exe
Gamewall16=warframe.png

Gamename17=Nier Automata
Gamecover17=nier.png
Gamedir17=D:\Program Files\NieR - Automata\NieRAutomata.exe
Gamewall17=nier.jpg

Gamename18=The Witcher 3 - Wild Hunt
Gamecover18=witcher3.png
Gamewall18=witcher3.png
Gamedir18=D:\Program Files\The Witcher 3 - Wild Hunt\bin\x64\witcher3.exe

Gamename19=Battlefield 4
Gamecover19=bf4.png
Gamewall19=bf4.jpg
Gamedir19=D:\Program Files\Battlefield 4\bf4.exe

Gamename20=Kerbal Space Program
Gamecover20=kerbal.png
Gamewall20=kerbal.jpg
Gamedir20=D:\Program Files\Kerbal Space Program Making History\KSP_x64.exe
