[MeterShapes1]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(0*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle1]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(0*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename1#
MouseOverAction=[!ShowMeter MeterShapes1][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover1#"]
MouseLeaveAction=[!HideMeter MeterShapes1][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 1"]


[MeterShapes2]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(1*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle2]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(1*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename2#
MouseOverAction=[!ShowMeter MeterShapes2][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover2#"]
MouseLeaveAction=[!HideMeter MeterShapes2][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 2"]

[MeterShapes3]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(2*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle3]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(2*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename3#
MouseOverAction=[!ShowMeter MeterShapes3][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover3#"]
MouseLeaveAction=[!HideMeter MeterShapes3][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 3"]

[MeterShapes4]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(3*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle4]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(3*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename4#
MouseOverAction=[!ShowMeter MeterShapes4][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover4#"]
MouseLeaveAction=[!HideMeter MeterShapes4][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 4"]

[MeterShapes5]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(4*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle5]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(4*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename5#
MouseOverAction=[!ShowMeter MeterShapes5][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover5#"]
MouseLeaveAction=[!HideMeter MeterShapes5][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 5"]

[MeterShapes6]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(5*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle6]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(5*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename6#
MouseOverAction=[!ShowMeter MeterShapes6][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover6#"]
MouseLeaveAction=[!HideMeter MeterShapes6][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 6"]

[MeterShapes7]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(6*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle7]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(6*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename7#
MouseOverAction=[!ShowMeter MeterShapes7][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover7#"]
MouseLeaveAction=[!HideMeter MeterShapes7][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 7"]

[MeterShapes8]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(7*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle8]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(7*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename8#
MouseOverAction=[!ShowMeter MeterShapes8][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover8#"]
MouseLeaveAction=[!HideMeter MeterShapes8][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 8"]


[MeterShapes9]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(8*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle9]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(8*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename9#
MouseOverAction=[!ShowMeter MeterShapes9][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover9#"]
MouseLeaveAction=[!HideMeter MeterShapes9][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 9"]


[MeterShapes10]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(9*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle10]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(9*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename10#
MouseOverAction=[!ShowMeter MeterShapes10][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover10#"]
MouseLeaveAction=[!HideMeter MeterShapes10][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 10"]

[MeterShapes11]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(10*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle11]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(10*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename11#
MouseOverAction=[!ShowMeter MeterShapes11][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover11#"]
MouseLeaveAction=[!HideMeter MeterShapes11][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 11"]

[MeterShapes12]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(11*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle12]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(11*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename12#
MouseOverAction=[!ShowMeter MeterShapes12][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover12#"]
MouseLeaveAction=[!HideMeter MeterShapes12][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 12"]

[MeterShapes13]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(12*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle13]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(12*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename13#
MouseOverAction=[!ShowMeter MeterShapes13][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover13#"]
MouseLeaveAction=[!HideMeter MeterShapes13][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 13"]

[MeterShapes14]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(13*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle14]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(13*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename14#
MouseOverAction=[!ShowMeter MeterShapes14][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover14#"]
MouseLeaveAction=[!HideMeter MeterShapes14][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 14"]


[MeterShapes15]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(14*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle15]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(14*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename15#
MouseOverAction=[!ShowMeter MeterShapes15][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover15#"]
MouseLeaveAction=[!HideMeter MeterShapes15][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 15"]

[MeterShapes16]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(15*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle16]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(15*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename16#
MouseOverAction=[!ShowMeter MeterShapes16][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover16#"]
MouseLeaveAction=[!HideMeter MeterShapes16][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 16"]


[MeterShapes17]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(16*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle17]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(16*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename17#
MouseOverAction=[!ShowMeter MeterShapes17][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover17#"]
MouseLeaveAction=[!HideMeter MeterShapes17][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 17"]


[MeterShapes18]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(17*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle18]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(17*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename18#
MouseOverAction=[!ShowMeter MeterShapes18][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover18#"]
MouseLeaveAction=[!HideMeter MeterShapes18][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 18"]


[MeterShapes19]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(18*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle19]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(18*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename19#
MouseOverAction=[!ShowMeter MeterShapes19][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover19#"]
MouseLeaveAction=[!HideMeter MeterShapes19][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 19"]


[MeterShapes20]
Group=Shapes
Meter=Shape
Hidden=1
X=0
Y=(19*(#Space#))+([SmoothScroll])
Shape=Rectangle 0,0,#BannerWidth#,#BannerHeight# | Fill Color #Color#,250 | StrokeWidth 0
DynamicVariables=1
[GameTitle20]
Meter=String
MeterStyle=GameTitle
X=#NameX#
Y=(19*(#Space#))+(#BannerHeight#/2)+([SmoothScroll])
Text=#Gamename20#
MouseOverAction=[!ShowMeter MeterShapes20][!SetOption #CURRENTSECTION# FontColor "0,0,0"][Play "#@#Sounds\Hover.wav"][!SetOption GameCover ImageName "#@#Spectrum\#Gamecover20#"]
MouseLeaveAction=[!HideMeter MeterShapes20][!SetOption #CURRENTSECTION# FontColor "#Color#"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 20"]

[GameCover]
Meter=Image
MeterStyle=GameIcon
X=(#CURRENTCONFIGWIDTH#*0.7)
Y=0
W=(#CURRENTCONFIGWIDTH#*0.3)
H=(#CURRENTCONFIGHEIGHT#*0.8)
SolidColor=0,0,0,20
PreserveAspectRatio=1
ImageTint=#Color#
MaskImagePath=#@#\
MaskImageName=lines.png