[Game1]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover1#
X=([SmoothScroll])+(#Space#)*Trunc(0/#Rows#)
Y=((0%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "1"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 1"]


[Game2]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover2#
X=([SmoothScroll])+(#Space#)*Trunc(1/#Rows#)
Y=((1%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "2"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 2"]

[Game3]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover3#
X=([SmoothScroll])+(#Space#)*Trunc(2/#Rows#)
Y=((2%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "3"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 3"]

[Game4]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover4#
X=([SmoothScroll])+(#Space#)*Trunc(3/#Rows#)
Y=((3%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "4"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 4"]

[Game5]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover5#
X=([SmoothScroll])+(#Space#)*Trunc(4/#Rows#)
Y=((4%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "5"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 5"]

[Game6]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover6#
X=([SmoothScroll])+(#Space#)*Trunc(5/#Rows#)
Y=((5%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "6"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 6"]

[Game7]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover7#
X=([SmoothScroll])+(#Space#)*Trunc(6/#Rows#)
Y=((6%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "7"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 7"]

[Game8]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover8#
X=([SmoothScroll])+(#Space#)*Trunc(7/#Rows#)
Y=((7%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "8"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 8"]

[Game9]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover9#
X=([SmoothScroll])+(#Space#)*Trunc(8/#Rows#)
Y=((8%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "9"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 9"]

[Game10]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover10#
X=([SmoothScroll])+(#Space#)*Trunc(9/#Rows#)
Y=((9%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "10"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 10"]

[Game11]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover11#
X=([SmoothScroll])+(#Space#)*Trunc(10/#Rows#)
Y=((10%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "11"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 11"]

[Game12]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover12#
X=([SmoothScroll])+(#Space#)*Trunc(11/#Rows#)
Y=((11%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "12"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 12"]

[Game13]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover13#
X=([SmoothScroll])+(#Space#)*Trunc(12/#Rows#)
Y=((12%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "13"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 13"]

[Game14]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover14#
X=([SmoothScroll])+(#Space#)*Trunc(13/#Rows#)
Y=((13%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "14"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 14"]

[Game15]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover15#
X=([SmoothScroll])+(#Space#)*Trunc(14/#Rows#)
Y=((14%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "15"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 15"]

[Game16]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover16#
X=([SmoothScroll])+(#Space#)*Trunc(15/#Rows#)
Y=((15%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "16"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 16"]

[Game17]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover17#
X=([SmoothScroll])+(#Space#)*Trunc(16/#Rows#)
Y=((16%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "17"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 17"]

[Game18]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover18#
X=([SmoothScroll])+(#Space#)*Trunc(17/#Rows#)
Y=((17%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "18"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 18"]

[Game19]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover19#
X=([SmoothScroll])+(#Space#)*Trunc(18/#Rows#)
Y=((18%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "19"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 19"]

[Game20]
Meter=Image
MeterStyle=GameIcon
ImageName=#@#App\#Gamecover20#
X=([SmoothScroll])+(#Space#)*Trunc(19/#Rows#)
Y=((19%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#
MouseOverAction=[Play "#@#Sounds\Hover.wav"][!SetVariable Select "20"][!SetOption #CURRENTSECTION# ImageTint "0,0,0"][!SetOption #CURRENTSECTION# SolidColor "#Color#"]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "#Color#"][!SetOption #CURRENTSECTION# SolidColor "0,0,0,30"]
LeftMouseUpAction=!Execute [!CommandMeasure InputExecute "Execute 20"]

[GameTitle1]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(0/#Rows#)+(#BannerWidth#/2)
Y=((0%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename1#

[GameTitle2]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(1/#Rows#)+(#BannerWidth#/2)
Y=((1%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename2#

[GameTitle3]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(2/#Rows#)+(#BannerWidth#/2)
Y=((2%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename3#

[GameTitle4]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(3/#Rows#)+(#BannerWidth#/2)
Y=((3%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename4#

[GameTitle5]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(4/#Rows#)+(#BannerWidth#/2)
Y=((4%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename5#

[GameTitle6]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(5/#Rows#)+(#BannerWidth#/2)
Y=((5%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename6#

[GameTitle7]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(6/#Rows#)+(#BannerWidth#/2)
Y=((6%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename7#

[GameTitle8]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(7/#Rows#)+(#BannerWidth#/2)
Y=((7%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename8#

[GameTitle9]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(8/#Rows#)+(#BannerWidth#/2)
Y=((8%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename9#

[GameTitle10]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(9/#Rows#)+(#BannerWidth#/2)
Y=((9%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename10#

[GameTitle11]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(10/#Rows#)+(#BannerWidth#/2)
Y=((10%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename11#

[GameTitle12]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(11/#Rows#)+(#BannerWidth#/2)
Y=((11%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename12#

[GameTitle13]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(12/#Rows#)+(#BannerWidth#/2)
Y=((12%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename13#

[GameTitle14]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(13/#Rows#)+(#BannerWidth#/2)
Y=((13%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename14#

[GameTitle15]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(14/#Rows#)+(#BannerWidth#/2)
Y=((14%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename15#

[GameTitle16]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(15/#Rows#)+(#BannerWidth#/2)
Y=((15%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename16#

[GameTitle17]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(16/#Rows#)+(#BannerWidth#/2)
Y=((16%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename17#

[GameTitle18]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(17/#Rows#)+(#BannerWidth#/2)
Y=((17%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename18#

[GameTitle19]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(18/#Rows#)+(#BannerWidth#/2)
Y=((18%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename19#

[GameTitle20]
Meter=String
MeterStyle=GameTitle
X=([SmoothScroll])+(#Space#)*Trunc(19/#Rows#)+(#BannerWidth#/2)
Y=((19%#Rows#)*(#BannerHeight#+#Rowspace#))-[SmoothTransition]+#CURRENTCONFIGHEIGHT#-#NameY#+#BannerHeight#
Text=#Gamename20#
